services:
  db:
    image: public.ecr.aws/docker/library/postgres:14.15-alpine3.21
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 1s
      timeout: 5s
      retries: 10
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    image: .
    container_name: nq-api
    ports:
      - "8001:80"
    depends_on:
      - db
      - forced-alignment
    volumes:
      - static:/app/staticfiles
    environment:
      SECRET_KEY: bruh
      DEBUG: 1
      DJANGO_LOGLEVEL: info
      DJANGO_ALLOWED_HOSTS: localhost
      CSRF_TRUSTED_ORIGINS: http://localhost:8001
      DATABASE_NAME: postgres
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      FORCED_ALIGNMENT_API_URL: http://forced-alignment:5000

  frontend-proxy:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - static:/static:ro
    depends_on:
      - api
  forced-alignment:
    image: natiqquran/forced-alignment
    container_name: forced-alignment
volumes:
  postgres_data:
  static:
